// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FormErrors: typeof import('./../src/components/form/FormErrors.vue')['default']
    FormPreFormData: typeof import('./../src/components/form/FormPreFormData.vue')['default']
    FormProvider: typeof import('./../src/components/form/FormProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
